const Images = {
  logo: require('../assets/Logo.png'),
  RectangleFirst: require("../assets/RectangleFirst.png"),
  RectangleSecond: require("../assets/RectangleSecond.png"),
  Google: require("../assets/Google.png"),
  Facbook: require("../assets/Facbook.png"),
  Group: require("../assets/Group.png"),
  OpenEyes: require("../assets/OpenEyes.png"),
  ClosedEyes: require("../assets/ClosedEyes.png"),
  buttonLeft: require("../assets/buttonLeft.png"),
  buttonRight: require("../assets/buttonRight.png"),
  Check: require("../assets/Check.png"),
  Uncheck: require("../assets/Unchek.png"),
  Camera: require("../assets/Camera.png"),
  userLogo: require("../assets/userLogo.png"),
  Polygon: require("../assets/Polygon.png"),
   calender: require("../assets/calender.png"),
     Speaker: require('../assets/Speaker.png'),
  Unmute: require('../assets/Unmute.png'),
  SendGifts: require('../assets/SendGifts.png'),
  End: require('../assets/End.png'),
  Cameraoff: require('../assets/Cameraoff.png'),
  FlipCamera: require('../assets/FlipCamera.png'),
    Cameraon: require('../assets/CameraOn.png'),
    Checkyes:require("../assets/Checkyes.png"),
    Search: require('../assets/Search.png'),
    LeftArrow: require('../assets/LeftArrow.png'),
    RightArrow:require("../assets/RightArrow.png"),   
    location:require("../assets/location.png"),
    notifictionball: require('../assets/notifictionball.png'),
    cemraLogo: require('../assets/cemraLogo.png'),
    Microphone:require("../assets/Microphone.png"),
      PhotoGallery:require("../assets/PhotoGallery.png"),
            Contact:require("../assets/Contact.png"),
             Ellipse: require('../assets/Ellipse.png'),
    Mask:require("../assets/Mask.png"),
      Union:require("../assets/Union.png"),
            MaskGroup:require("../assets/MaskGroup.png"),
            materialError:require("../assets/materialError.png"),
};

export default Images;
